import { action, requestId, escapeText as e } from './api.js';
const X='<svg viewBox="0 0 16 16" width="12" height="12" fill="none" stroke="currentColor" stroke-width="1.5" aria-hidden="true"><path d="m4 4 8 8m0-8-8 8"/></svg>';
const pathPrefix='piclaw://addon/code-review/';
type DraftState={body:string;threadId?:string;range?:{startLine:number;endLine:number};side:string;draftId?:string;version?:number;requestId:string};
const button=(name:string,label:string,title:string,extra='')=>`<button type="button" data-action="${name}" title="${e(title)}" ${extra}>${label}</button>`;
/** One real pane. All mutations use authenticated APIs; no model runs are triggered by mounting. */
export class CodeReviewPane {
 private element:HTMLElement;private abort=new AbortController();private disposed=false;private dirtyCallback:((value:boolean)=>void)|null=null;private dirty=false;
 private reviewId:string;private review:any;private snapshots:any[]=[];private snapshotId='';private files:any[]=[];private fileId='';private content:any;private targets:any[]=[];private threads:any[]=[];private selected=new Set<string>();private detail=new Map<string,any>();private projections=new Map<string,any>();private fileScroll=new Map<string,number>();private selection:{startLine:number;endLine:number;side:string}|null=null;private composer:DraftState|null=null;private draftTimer:ReturnType<typeof setTimeout>|undefined;private savedDrafts:any[]=[];private savingDraft=false;private draftPromise:Promise<void>|null=null;private editMessage:any=null;private draftEpoch=0;private busy=false;private pendingPayload:Record<string,unknown>|null=null;private commentThreadVersion:number|undefined;
 private view:'source'|'unified'|'split'='source';private wrap=false;private showFiles=false;private drawer:'threads'|'send'|null=null;private sendIntent:string|null=null;private summary='';private activeTarget:any=null;private status='';private fileFilter='';private threadFilter='all';private page=0;private loadEpoch=0;private loading=false;private observer:ResizeObserver;private moreMenu=false;private loadError='';
 constructor(container:HTMLElement,context:any){
  this.reviewId=String(context.path||'').slice(pathPrefix.length);if(!/^[\w-]+$/.test(this.reviewId))throw Error('Invalid review path.');
  this.element=container.ownerDocument.createElement('section');this.element.className='cr-pane';this.element.setAttribute('aria-label','Code Review');container.append(this.element);
  this.element.addEventListener('click',this.click);this.element.addEventListener('change',this.change);this.element.addEventListener('input',this.input);this.element.addEventListener('keydown',this.keydown);
  this.observer=new ResizeObserver(entries=>{const width=entries[0]?.contentRect.width??1200;this.element.dataset.narrow=String(width<720);this.element.dataset.medium=String(width<1100);if(width<1100&&this.view==='split'){this.view='unified';this.render();}});this.observer.observe(this.element);this.render();void this.load();
 }
 getContent(){return undefined;}isDirty(){return this.dirty;}onDirtyChange(callback:(value:boolean)=>void){this.dirtyCallback=callback;}focus(){if(!this.review)void this.load();else this.element.querySelector<HTMLElement>('button,select')?.focus();}resize(){}
 exportHostTransferState(){return{reviewId:this.reviewId,fileId:this.fileId,snapshotId:this.snapshotId,view:this.view,scroll:this.element.querySelector('.cr-source')?.scrollTop||0};}
 async beforeDetachFromHost(){await this.persistDraft();if(this.dirty)throw Error('Save or explicitly discard the comment draft before detaching.');}
 dispose(){if(this.disposed)return;this.disposed=true;this.abort.abort();clearTimeout(this.draftTimer);this.observer.disconnect();this.element.remove();}
 private setDirty(value:boolean){this.dirty=value;this.dirtyCallback?.(value);}
 private async api<T=any>(name:string,payload:Record<string,unknown>={}){return action<T>(name,{reviewId:this.reviewId,...payload},this.abort.signal);}
 private fail(error:unknown){if(this.disposed||(error as Error)?.name==='AbortError')return;this.status=(error as Error)?.message||'Review action failed.';this.render();}
 private async load(){if(this.disposed)return;this.loading=true;try{
  [this.review,this.targets,this.snapshots,this.threads,this.savedDrafts]=await Promise.all([this.api('review'),this.api('targets'),this.api('snapshots'),this.api('threads'),this.api('drafts')]);
  const target=JSON.parse(this.review.target_json);this.activeTarget??=target;
  this.snapshotId ||= this.snapshots[0]?.id||'';this.loadError='';await this.loadFiles();
 }catch(error){this.loadError=(error as Error).message;this.fail(error);}finally{this.loading=false;this.render();}}
 private async loadFiles(){if(!this.snapshotId)return;this.files=await this.api('files',{snapshotId:this.snapshotId});if(!this.files.some(f=>f.id===this.fileId))this.fileId=this.files[0]?.id||'';this.page=0;await this.loadContent();}
 private async loadContent(){const epoch=++this.loadEpoch;if(!this.fileId){this.content=null;return;}
  const fileId=this.fileId;const response=await this.api('file',{fileId,offset:this.page*300,limit:300});if(epoch!==this.loadEpoch||this.disposed)return;this.content=response;this.view=response.change_kind==='source'?'source':this.view==='source'?'unified':this.view;
  this.projections.clear();for(const thread of this.threads){try{const projection=await this.api('projection',{threadId:thread.id,fileId});if(epoch!==this.loadEpoch)return;this.projections.set(thread.id,projection);}catch{/* Other-file or unavailable projection stays out of this view. */}}
  this.render();}
 private async reloadThreads(){this.threads=await this.api('threads');for(const thread of this.threads){if(this.detail.has(thread.id))this.detail.set(thread.id,await this.api('thread',{threadId:thread.id}));}for(const id of this.selected)if(!this.threads.some(t=>t.id===id&&t.state==='open'))this.selected.delete(id);await this.loadContent();}
 private async openThread(threadId:string){this.detail.set(threadId,await this.api('thread',{threadId}));this.render();}
 private relevant(thread:any){const anchor=thread.anchor;const p=this.projections.get(thread.id);return anchor.snapshotFileId===this.fileId||p?.status==='exact'||p?.status==='moved';}
 private threadRows(){return this.threads.filter(t=>this.relevant(t)&&t.state!=='deleted');}
 private threadHtml(thread:any){const data=this.detail.get(thread.id),anchor=thread.anchor,p=this.projections.get(thread.id);const first=data?.messages?.find((m:any)=>m.body)?.body||'Open discussion';const location=anchor.scope==='file'?'Whole file':`${p?.side||anchor.side} lines ${p?.startLine??anchor.startLine}–${p?.endLine??anchor.endLine}`;
  return `<article class="cr-thread" id="cr-${thread.id}"><header><label title="Select this concern for a later explicit send. Does not send or resolve it."><input type="checkbox" data-pick="${thread.id}" ${this.selected.has(thread.id)?'checked':''} ${thread.state!=='open'?'disabled':''} title="Include this thread in the next review sent to the agent.">Include in send</label><strong>${e(thread.state)}</strong><span class="cr-muted">${e(location)}${p?.status==='moved'?' · moved since review':''}</span>${button('expand','Discussion',data?'Collapse this discussion.':'Load public messages and replies.',`data-thread="${thread.id}"`)}</header>${data?`<div class="cr-messages">${data.messages.map((m:any)=>`<div class="cr-message"><strong>${e(m.author_kind==='agent'?'Agent':'You')}</strong> <small>${e(m.updated_at)}${m.version>1?' · edited':''}</small><p>${e(m.body??'Comment deleted')}</p>${m.author_kind==='operator'&&!m.deleted?button('edit','Edit','Edit your message; this does not send updated instructions.',`data-message="${m.id}" data-thread="${thread.id}"`)+button('delete-message','Delete','Delete this message body while retaining its replies.',`data-message="${m.id}" data-thread="${thread.id}" data-settings-button="danger"`):''}</div>`).join('')}</div><footer>${button('reply','Reply',thread.state==='resolved'?'Reopen this thread before replying.':'Write a reply without starting agent work.',`data-thread="${thread.id}" ${thread.state==='resolved'?'disabled':''}`)}${button(thread.state==='resolved'?'reopen':'resolve',thread.state==='resolved'?'Reopen':'Resolve','Change concern state explicitly; queued work is not cancelled.',`data-thread="${thread.id}"`)}${button('send-thread','Send thread','Preview this concern before sending to its bound local agent.',`data-thread="${thread.id}" ${thread.state!=='open'?'disabled':''}`)}${button('reassign','Reassign','Bind this thread explicitly to the selected toolbar target; old work is not cancelled.',`data-thread="${thread.id}"`)}${button('delete-thread','Delete thread','Confirm removing this discussion; already delivered work cannot be recalled.',`data-thread="${thread.id}" data-settings-button="danger"`)}</footer>`:`<div class="cr-message cr-muted">${e(first)}</div>`}</article>`;
 }
 private codeLine(side:string,line:number|null,kind:string,text:string){if(line===null)return '<div class="cr-line cr-blank"></div>';const lines=side==='old'?this.content.old.lines:this.content.new.lines;const token=lines.find((x:any)=>x.number===line);const html=token?.text===text?token.html:e(text);const sel=this.selection?.side===side&&line>=this.selection.startLine&&line<=this.selection.endLine;
  return `<div class="cr-line ${kind} ${sel?'selected':''}" data-line="${line}" data-side="${side}"><button data-action="line-comment" data-side="${side}" data-line="${line}" title="Add guidance on ${side} line ${line}. No work starts until sent." aria-label="Comment on line ${line}" data-settings-button="unstyled">+</button><button data-action="select-line" data-line="${line}" data-side="${side}" title="Select this line; Shift-click or select another line to extend the range." data-settings-button="unstyled">${line}</button><span aria-hidden="true">${kind==='added'?'+':kind==='deleted'?'−':''}</span><code>${html}</code></div>`;
 }
 private codeHtml(){if(!this.content)return '<p class="cr-empty">No source is available for this snapshot.</p>';const c=this.content,rows=c.diff||c.new.lines.map((line:any)=>({kind:'context',oldLine:null,newLine:line.number,text:line.text}));const mounted=new Set<string>();let html='';
  for(const row of rows){const side=this.view==='source'?'source':row.kind==='deleted'?'old':'new';if(this.view==='split')html+=`<div class="cr-pair">${this.codeLine('old',row.oldLine,row.kind,row.text)}${this.codeLine('new',row.newLine,row.kind,row.text)}</div>`;else html+=this.codeLine(side,row.kind==='deleted'?row.oldLine:row.newLine,row.kind,row.text);
   for(const thread of this.threadRows()){if(mounted.has(thread.id))continue;const anchor=thread.anchor,p=this.projections.get(thread.id),end=p?.endLine??anchor.endLine,ts=p?.side||anchor.side;if(anchor.scope==='range'&&end===(ts==='old'?row.oldLine:row.newLine)){html+=this.threadHtml(thread);mounted.add(thread.id);}}
  }
  for(const thread of this.threadRows())if(!mounted.has(thread.id)&&thread.anchor.scope==='file')html+=this.threadHtml(thread);return html;
 }
 private render(){if(this.disposed)return;const active=this.element.ownerDocument.activeElement as HTMLInputElement;const focusId=active?.closest('.cr-pane')===this.element?active.id:'';const selectionStart=active?.selectionStart,selectionEnd=active?.selectionEnd;const previousScroll=this.element.querySelector('.cr-source')?.scrollTop||this.fileScroll.get(this.fileId)||0;
  if(!this.review){this.element.innerHTML=`<div class="cr-empty">${e(this.loadError||'Loading review…')}${this.loadError?button('load','Retry','Retry loading this review without sending work.'):''}</div>`;return;}
  const c=this.content,path=c?.new_path||c?.old_path||this.review.focus_path,snapshot=this.snapshots.find(s=>s.id===this.snapshotId);const fileRows=this.files.filter(f=>(f.new_path||f.old_path||'').toLowerCase().includes(this.fileFilter.toLowerCase()));
  this.element.innerHTML=`<div class="cr-toolbar">${button('files','Files','Show the files in this review.')}<select id="cr-snapshot" title="Choose an immutable saved-source or Git comparison snapshot.">${this.snapshots.map(s=>`<option value="${s.id}" ${s.id===this.snapshotId?'selected':''} title="${e(s.mode+' captured '+s.captured_at)}">${e(s.mode+' · '+s.captured_at.slice(11,19))}</option>`).join('')}</select><span class="cr-grow"></span><select id="cr-target" title="Choose a local target. Existing thread assignments require explicit reassignment.">${this.targets.map(t=>`<option value="${e(t.chatJid)}" ${t.chatJid===this.activeTarget?.chatId?'selected':''}>${e(t.label)}</option>`).join('')}</select>${button('threads',`Threads (${this.threads.length})`,'Browse saved open, resolved and outdated concerns.')}${button('send',`Send to agent${this.selected.size?' ('+this.selected.size+')':''}`,this.selected.size?'Preview selected guidance before queueing one review.':'Include at least one open thread to send.',`data-settings-button="primary" ${!this.selected.size?'disabled':''}`)}<div class="cr-options">${button('options','⋯','View and capture options.','data-settings-button="icon" aria-label="View options"')}${this.moreMenu?`<div class="cr-menu">${button('refresh','Refresh saved source','Capture the newest saved bytes; comments retain original anchors.')}${button('wrap','Wrap long lines','Toggle visual wrapping without changing saved source.')}${button('layout',this.view==='split'?'Unified diff':'Split diff','Switch diff layout; unavailable in source mode.',this.view==='source'?'disabled':'')}${button('staged','Staged changes','Capture HEAD to index without staging or writing source.')}${button('unstaged','Working changes','Capture index to saved worktree, including untracked text files.')}${button('history','Recent commits','Select a bounded file-history commit to review.')}${button('add-file','Add file','Add another saved workspace file to this review explicitly.')}${button('drafts',`Drafts (${this.savedDrafts.length})`,'Restore an acknowledged private comment draft.')}${button('receipts','Delivery receipts','Inspect queued, failed and unknown attempts without resending.')}</div>`:''}</div></div>
  ${this.status?`<div class="cr-status" role="status">${e(this.status)}${button('dismiss',X,'Dismiss status.','data-settings-button="icon" aria-label="Dismiss status"')}</div>`:''}
  <div class="cr-body"><nav class="cr-files ${this.showFiles?'open':''}" ${this.files.length<2&&!this.showFiles?'hidden':''}><header>Files ${button('files',X,'Close the file list.','data-settings-button="icon" aria-label="Close file list"')}</header><input id="cr-filter" value="${e(this.fileFilter)}" placeholder="Filter paths" title="Filter paths in this snapshot without deleting anything.">${fileRows.map(f=>button('file',`<span>${e(f.new_path||f.old_path)}</span><small>${e(f.change_kind)}</small>`,'View this saved file without sending its comments.',`data-file="${f.id}" class="${f.id===this.fileId?'active':''}" data-settings-button="unstyled"`)).join('')}</nav>
  <main class="cr-main"><header class="cr-file-header"><strong>${e(path)}</strong><span class="cr-grow cr-muted">${e(snapshot?.mode||'')} · ${e((c?.new_hash||c?.old_hash||'').slice(0,10))} · ${e(c?.new?.language||'text')}${c?.new&&!c.new.highlighted?' (plain)':''}</span>${button('file-comment','Comment on file','Create guidance about the whole file without selecting lines.')}</header><div class="cr-source ${this.wrap?'wrap':''}" tabindex="0">${this.codeHtml()}</div>
  <div class="cr-pagination">${button('previous','Previous lines','Load the previous bounded source/diff page.',this.page===0?'disabled':'')}<span>${this.page*300+1}–${this.page*300+(c?.diff?.length??c?.new?.lines.length??0)}</span>${button('next','Next lines','Load the next bounded source/diff page.',((this.page+1)*300>=(c?.diffTotal||Math.max(c?.old.total||0,c?.new.total||0)))?'disabled':'')}</div>
  ${this.selection?`<div class="cr-selection">${e(this.selection.side)} lines ${this.selection.startLine}–${this.selection.endLine}${button('range-comment','Add comment','Comment on the selected saved range.')}${button('clear-range','Clear','Clear selection only; comments remain.')}${button('reanchor','Re-anchor thread','Explicitly map a chosen thread to this selected range.')}</div>`:''}
  ${this.composer?`<section class="cr-composer"><strong>${this.editMessage?'Edit message':this.composer.threadId?'Reply':this.composer.range?'Range comment':'File comment'}</strong><textarea id="cr-body" title="Write public guidance; posting does not send it to an agent." placeholder="What should change or be checked?">${e(this.composer.body)}</textarea><footer><small>${this.dirty?'Draft not yet saved':'Draft saved'}</small><span class="cr-grow"></span>${button('cancel','Cancel','Discard this unpublished text with confirmation if needed.')}${button('post',this.editMessage?'Save edit':'Post comment','Save guidance without queueing agent work.','data-settings-button="primary"')}</footer></section>`:''}</main></div>
  ${this.drawer?`<div class="cr-backdrop" data-action="close-drawer"></div><aside class="cr-drawer" role="dialog" aria-modal="true" aria-label="Review threads"><header><strong>${this.drawer==='send'?'Send selected review':'Threads'}</strong>${button('close-drawer',X,'Close without sending; keep the selection.','data-settings-button="icon" aria-label="Close review drawer"')}</header><select id="cr-thread-filter" title="Filter concerns without changing their state.">${['all','open','resolved','outdated'].map(v=>`<option ${v===this.threadFilter?'selected':''}>${v}</option>`).join('')}</select>${this.threads.filter(t=>this.threadFilter==='all'||this.threadFilter===t.state||this.threadFilter==='outdated'&&!this.relevant(t)).map(t=>`<div class="cr-drawer-item"><label><input type="checkbox" data-pick="${t.id}" ${this.selected.has(t.id)?'checked':''} ${t.state==='resolved'?'disabled':''} title="Include this concern in the next explicit send. Does not resolve it.">Include in send</label><strong>${e(t.state)}</strong><small>${e(t.id.slice(-8))} · ${e(t.anchor.side)} ${t.anchor.startLine??'file'}</small>${button('jump','Open discussion','Reveal original source and public messages.',`data-thread="${t.id}"`)}</div>`).join('')}${this.drawer==='send'?`<textarea id="cr-summary" title="Optional overall instruction sent with selected thread references." placeholder="Overall guidance (optional)">${e(this.summary)}</textarea><p>Queue to ${e(this.activeTarget?.label)} behind current work. No interruption.</p>${button('confirm-send','Queue selected review','Queue one review; replies and resolutions remain per thread.',`data-settings-button="primary" ${!this.selected.size?'disabled':''}`)}`:''}</aside>`:''}`;
  const source=this.element.querySelector('.cr-source');if(source)source.scrollTop=previousScroll;
  if(focusId){const next=this.element.querySelector<HTMLElement>('#'+focusId);next?.focus();if(next instanceof HTMLTextAreaElement||next instanceof HTMLInputElement)try{next.setSelectionRange(selectionStart,selectionEnd);}catch{}}
 }
 private compose(threadId?:string){this.draftEpoch++;const range=this.selection?{startLine:this.selection.startLine,endLine:this.selection.endLine}:undefined;this.composer={body:'',threadId,range:threadId?undefined:range,side:this.selection?.side||(this.view==='source'?'source':'new'),requestId:requestId()};if(this.selection&&!threadId)this.composer.side=this.selection.side;this.editMessage=null;this.commentThreadVersion=threadId?this.threads.find(t=>t.id===threadId)?.version:undefined;this.setDirty(false);this.render();this.element.querySelector<HTMLTextAreaElement>('#cr-body')?.focus();}
 private async persistDraft(){if(this.draftPromise)return this.draftPromise;this.draftPromise=this.writeDraft().finally(()=>{this.draftPromise=null;});return this.draftPromise;}
 private async writeDraft(){clearTimeout(this.draftTimer);if(!this.composer||!this.dirty||this.savingDraft||this.editMessage)return;const draft=this.composer,body=draft.body,epoch=this.draftEpoch;this.savingDraft=true;try{
  const saved=await this.api("draft",{draftId:draft.draftId,threadId:draft.threadId,...(!draft.threadId?{fileId:this.fileId,side:draft.side,range:draft.range}:{}),body,expectedVersion:draft.version,requestId:requestId()});if(epoch===this.draftEpoch&&this.composer===draft){draft.draftId=saved.draftId;draft.version=saved.version;this.setDirty(draft.body!==body);}
 }catch(error){this.fail(error);}finally{this.savingDraft=false;}}
 private click=(event:Event)=>{const el=(event.target as Element).closest<HTMLElement>('[data-action]');if(!el||el.matches(':disabled')||this.busy)return;event.preventDefault();this.busy=true;void this.perform(el.dataset.action!,el).catch(error=>this.fail(error)).finally(()=>{this.busy=false;});};
 private async perform(name:string,el:HTMLElement){const t=()=>this.threads.find(t=>t.id===el.dataset.thread);if(name!=='options')this.moreMenu=false;
  switch(name){
   case 'load':await this.load();return;case 'dismiss':this.status='';break;case 'options':this.moreMenu=!this.moreMenu;break;case 'files':this.showFiles=!this.showFiles;break;
   case 'file':if(this.dirty){this.status='Save or discard the current comment before changing file.';break;}this.fileScroll.set(this.fileId,this.element.querySelector('.cr-source')?.scrollTop||0);this.fileId=el.dataset.file!;this.page=0;this.selection=null;this.composer=null;await this.loadContent();return;
   case 'wrap':this.wrap=!this.wrap;break;case 'layout':this.view=this.view==='split'?'unified':'split';break;
   case 'previous':this.page=Math.max(0,this.page-1);await this.loadContent();return;case 'next':this.page++;await this.loadContent();return;
   case 'line-comment':this.selection={startLine:Number(el.dataset.line),endLine:Number(el.dataset.line),side:el.dataset.side!};this.compose();return;
   case 'select-line':{const line=Number(el.dataset.line),side=el.dataset.side!;this.selection=this.selection?.side===side?{side,startLine:Math.min(this.selection.startLine,line),endLine:Math.max(this.selection.endLine,line)}:{side,startLine:line,endLine:line};break;}
   case 'clear-range':this.selection=null;break;case 'file-comment':this.selection=null;this.compose();return;case 'range-comment':this.compose();return;
   case 'threads':this.drawer='threads';break;case 'close-drawer':this.drawer=null;this.sendIntent=null;break;
   case 'expand':if(this.detail.has(el.dataset.thread!))this.detail.delete(el.dataset.thread!);else await this.openThread(el.dataset.thread!);break;
   case 'jump':{const thread=t();this.drawer=null;const file=this.files.find(f=>f.id===thread.anchor.snapshotFileId);if(file)this.fileId=file.id;else this.status='Thread belongs to an earlier snapshot; choose its original capture from the snapshot selector.';await this.openThread(thread.id);await this.loadContent();this.element.querySelector('#cr-'+thread.id)?.scrollIntoView({block:'center'});return;}
   case 'reply':if(t().state==='resolved')throw Error('Reopen this concern first.');this.compose(t().id);return;
   case 'edit':{const thread=t();const message=this.detail.get(thread.id)?.messages.find((m:any)=>m.id===el.dataset.message);this.compose(thread.id);this.editMessage=message;this.composer!.body=message.body;this.render();return;}
   case 'cancel':if(this.composer?.body&&!confirm('Discard this unposted text?'))return;if(this.composer?.draftId)await this.api('deleteDraft',{draftId:this.composer.draftId,expectedVersion:this.composer.version,requestId:requestId()});this.draftEpoch++;this.composer=null;this.editMessage=null;this.setDirty(false);break;
   case 'post':{if(!this.composer?.body.trim())throw Error('Write guidance first.');clearTimeout(this.draftTimer);await this.draftPromise;const draft=this.composer;if(this.editMessage)await this.api('edit',{messageId:this.editMessage.id,expectedVersion:this.editMessage.version,body:draft.body,requestId:draft.requestId});else if(draft.threadId){await this.api('reply',{threadId:draft.threadId,expectedVersion:this.commentThreadVersion,body:draft.body,requestId:draft.requestId});}else await this.api('comment',{fileId:this.fileId,side:draft.side,range:draft.range,body:draft.body,requestId:draft.requestId});if(draft.draftId)await this.api('deleteDraft',{draftId:draft.draftId,expectedVersion:draft.version,requestId:requestId()});this.draftEpoch++;this.composer=null;this.editMessage=null;this.setDirty(false);this.status='Comment saved. No agent work queued.';await this.reloadThreads();return;}
   case 'delete-message':if(confirm('Delete your message body and retain replies?')){const message=this.detail.get(t().id).messages.find((m:any)=>m.id===el.dataset.message);await this.api('deleteMessage',{messageId:message.id,expectedVersion:message.version,confirm:true,requestId:requestId()});await this.reloadThreads();}return;
   case 'delete-thread':if(confirm('Delete this discussion? Already delivered work cannot be recalled.')){await this.api('deleteThread',{threadId:t().id,expectedVersion:t().version,confirm:true,requestId:requestId()});this.detail.delete(t().id);await this.reloadThreads();}return;
   case 'resolve':{const reason=prompt('Resolution explanation');if(reason===null)return;await this.api('resolve',{threadId:t().id,expectedVersion:t().version,explanation:reason,fileId:this.fileId,requestId:requestId()});await this.reloadThreads();return;}
   case 'reopen':await this.api('reopen',{threadId:t().id,expectedVersion:t().version,requestId:requestId()});await this.reloadThreads();return;
   case 'reassign':if(confirm(`Reassign this concern to ${this.activeTarget.label}?`)){await this.api('reassign',{threadId:t().id,target:this.activeTarget,expectedVersion:t().version,requestId:requestId()});await this.reloadThreads();}return;
   case 'send-thread':this.selected.clear();this.selected.add(t().id);this.activeTarget=t().target; // fall through
   case 'send':this.pendingPayload={target:{...this.activeTarget},items:this.selectionItems(),summary:this.summary};await this.api('preview',this.pendingPayload);this.sendIntent=requestId();this.drawer='send';break;
   case 'confirm-send':{const intent=this.sendIntent;if(!intent)throw Error('Preview the review before sending.');if(!this.pendingPayload)throw Error('Preview the review before sending.');const result=await this.api('send',{...this.pendingPayload,summary:this.summary,requestId:intent});const attempt=result.attempts.at(-1);this.status=`Review ${result.id}: ${attempt.state}. ${attempt.state==='accepted'?'Queued behind current work. No concern is resolved by queue acceptance.':'Inspect receipts before retrying.'}`;this.drawer=null;this.selected.clear();this.sendIntent=null;break;}
   case 'refresh':case 'staged':case 'unstaged':{if(this.dirty)throw Error('Save the pending comment draft before capturing a new source.');const mode=name==='refresh'?'source':name;const capture=await this.api('capture',{source:{path:this.review.focus_path,mode,includeUntracked:true},requestId:requestId()});this.snapshots=await this.api('snapshots');this.snapshotId=capture.snapshotId;this.fileId='';await this.loadFiles();return;}
   case 'history':{const rows=await this.api('history',{path:this.review.focus_path,limit:20});const pick=prompt(rows.map((r:any,i:number)=>`${i+1}. ${r.commit.slice(0,8)} ${r.subject}`).join('\n')+'\nCommit number');if(pick===null)return;const row=rows[Number(pick)-1];if(!row)throw Error('Select a listed commit.');let parent;if(row.parents.length>1){const number=prompt(row.parents.map((p:string,i:number)=>`${i+1}. ${p}`).join('\n')+'\nParent number');if(number===null)return;parent=row.parents[Number(number)-1];if(!parent)throw Error('Select a listed parent.');}const capture=await this.api('capture',{source:{path:this.review.focus_path,mode:'commit',commit:row.commit,parent},requestId:requestId()});this.snapshots=await this.api('snapshots');this.snapshotId=capture.snapshotId;await this.loadFiles();return;}
   case 'add-file':{const path=prompt('Saved workspace-relative file path');if(!path)return;const capture=await this.api('capture',{source:{path,mode:'source'},requestId:requestId()});this.snapshots=await this.api('snapshots');this.snapshotId=capture.snapshotId;this.fileId='';await this.loadFiles();return;}
   case 'drafts':{this.savedDrafts=await this.api('drafts');const pick=prompt(this.savedDrafts.map((d:any,i:number)=>`${i+1}. ${d.body.slice(0,80)}`).join('\n')+'\nDraft number');if(pick===null)return;const draft=this.savedDrafts[Number(pick)-1];if(!draft)throw Error('Select a saved draft.');const anchor=draft.anchor_json?JSON.parse(draft.anchor_json):null;if(anchor&&anchor.snapshotFileId!==this.fileId)throw Error('Open the draft’s original file snapshot first.');this.commentThreadVersion=draft.thread_id?this.threads.find(t=>t.id===draft.thread_id)?.version:undefined;this.composer={body:draft.body,threadId:draft.thread_id||undefined,side:anchor?.side||'source',range:anchor?.scope==='range'?{startLine:anchor.startLine,endLine:anchor.endLine}:undefined,draftId:draft.id,version:draft.version,requestId:requestId()};this.draftEpoch++;break;}
   case 'receipts':{const rows=await this.api('dispatches');const output=[];for(const row of rows.slice(0,10)){const d=await this.api('dispatch',{dispatchId:row.id});output.push(`${d.id}: ${d.attempts.at(-1)?.state}`);}this.status=output.join('\n')||'No delivery attempts.';break;}
   case 'reanchor':{if(!this.selection)throw Error('Select a saved range.');const id=prompt('Thread ID to re-anchor');if(!id)return;const thread=this.threads.find(t=>t.id===id);if(!thread)throw Error('Choose a thread in this review.');if(!confirm(thread.state==='resolved'?'Reopen and re-anchor this concern?':'Re-anchor this concern?'))return;await this.api('reanchor',{threadId:id,fileId:this.fileId,side:this.selection.side,range:{startLine:this.selection.startLine,endLine:this.selection.endLine},reopen:thread.state==='resolved',confirm:true,expectedVersion:thread.version,requestId:requestId()});await this.reloadThreads();return;}
  }
  this.render();
 }
 private selectionItems(){return [...this.selected].map(id=>{const t=this.threads.find(t=>t.id===id);return {threadId:id,version:t.version};});}
 private change=(event:Event)=>{const el=event.target as HTMLInputElement;if(!el.dataset.pick&&!['cr-target','cr-snapshot','cr-thread-filter'].includes(el.id))return;void(async()=>{if(el.dataset.pick){el.checked?this.selected.add(el.dataset.pick):this.selected.delete(el.dataset.pick);if(this.drawer==='send'){this.pendingPayload={target:{...this.activeTarget},items:this.selectionItems(),summary:this.summary};this.sendIntent=requestId();}}else if(el.id==='cr-target'){const selected=this.targets.find(t=>t.chatJid===el.value);this.activeTarget={chatId:selected.chatJid,incarnation:selected.incarnation,label:selected.label};this.sendIntent=null;}else if(el.id==='cr-snapshot'){if(this.dirty)throw Error('Save the comment draft first.');this.snapshotId=el.value;await this.loadFiles();}else if(el.id==='cr-thread-filter')this.threadFilter=el.value;this.render();})().catch(error=>this.fail(error));};
 private input=(event:Event)=>{const el=event.target as HTMLInputElement;if(el.id==='cr-body'&&this.composer){this.composer.body=el.value;this.setDirty(true);clearTimeout(this.draftTimer);this.draftTimer=setTimeout(()=>void this.persistDraft(),500);}else if(el.id==='cr-summary'){this.summary=el.value;if(this.drawer==='send'){this.sendIntent=requestId();}}else if(el.id==='cr-filter'){this.fileFilter=el.value;this.render();}};
 private keydown=(event:KeyboardEvent)=>{if((event.ctrlKey||event.metaKey)&&event.key.toLowerCase()==='s'){event.preventDefault();void this.persistDraft();}if(event.key==='Escape'){if(this.moreMenu){this.moreMenu=false;this.render();}else if(this.drawer){this.drawer=null;this.render();}}};
}
export const reviewPane={id:'code-review',label:'Code Review',capabilities:['readonly'],placement:'tabs',canHandle(context:any){return typeof context.path==='string'&&context.path.startsWith(pathPrefix)?100:false;},mount(container:HTMLElement,context:any){return new CodeReviewPane(container,context);}};
