import {test,expect} from 'bun:test';
import {mkdtempSync,rmSync} from 'node:fs';import {tmpdir} from 'node:os';import {join} from 'node:path';
import {ReviewService} from './dispatch.js';import type {SourceCapture,ReviewIdentity} from './contracts.js';
const who:ReviewIdentity={ownerId:'one',actorId:'operator',kind:'operator',workspaceId:'ws'};let serial=0;const m=(expectedVersion?:number)=>({requestId:'anchor-'+ ++serial,expectedVersion});
function fixture(){const dir=mkdtempSync(join(tmpdir(),'review-anchor-accept-')),store=new ReviewService(join(dir,'review.db'));const reviewId=store.createReview(who,{workspaceId:'ws',worktreeId:'wt',title:'R',focusPath:'src/main.ts',target:{chatId:'web:a',incarnation:'b1',label:'A'}},m()).reviewId;
 const snap=(text:string,path='src/main.ts',identity='inode1',oldPath:string|null=null)=>{const capture:SourceCapture={workspaceId:'ws',worktreeId:'wt',mode:'source',base:null,head:null,capturedAt:new Date().toISOString(),files:[{oldPath,newPath:path,oldText:oldPath?text:null,newText:text,change:oldPath?'renamed':'source',fileIdentity:identity}]};return store.capture(who,reviewId,capture,m()).files[0]!;};
 const file=snap('before\nstart\nconcern\nend\nafter\n');const thread=store.createThread(who,reviewId,{fileId:file,side:'source',range:{startLine:3,endLine:3},body:'Handle concern'},m());return{store,reviewId,file,thread,snap,close(){store.close();rmSync(dir,{recursive:true,force:true});}};}
test('CR-055 unrelated insertion projects uniquely and retains original open concern',()=>{const f=fixture();try{const original=f.store.getThread(who,f.thread.threadId);const next=f.snap('one\ntwo\nthree\nfour\nfive\nbefore\nstart\nconcern\nend\nafter\n');expect(f.store.project(who,f.thread.threadId,next)).toMatchObject({status:'moved',startLine:8,endLine:8});expect(f.store.getThread(who,f.thread.threadId)).toMatchObject({state:'open',anchor:original.anchor});expect(f.store.readFile(who,f.reviewId,f.file).newText).toBe('before\nstart\nconcern\nend\nafter\n');}finally{f.close();}});
test('CR-056 replaced anchored code is missing instead of reusing line numbers',()=>{const f=fixture();try{const next=f.snap('before\nstart\nreplacement\nend\nafter\n');expect(f.store.project(who,f.thread.threadId,next)).toMatchObject({status:'missing',startLine:null});expect(f.store.getThread(who,f.thread.threadId).anchor.selectedText).toBe('concern');expect(f.store.getThread(who,f.thread.threadId).state).toBe('open');}finally{f.close();}});
test('CR-057 duplicate context remains ambiguous and never picks a convenient block',()=>{const f=fixture();try{const block='before\nstart\nconcern\nend\nafter\n';const next=f.snap(block+'gap\n'+block);expect(f.store.project(who,f.thread.threadId,next)).toMatchObject({status:'ambiguous',startLine:null,endLine:null});expect(f.store.getThread(who,f.thread.threadId).anchor.startLine).toBe(3);}finally{f.close();}});
test('CR-058 explicit remapping records provenance without rewriting guidance',()=>{const f=fixture();try{const original=f.store.getThread(who,f.thread.threadId),next=f.snap('new\nrange\n');f.store.reanchor(who,f.thread.threadId,{fileId:next,side:'source',range:{startLine:1,endLine:2}},m(1));expect(f.store.project(who,f.thread.threadId,next)).toMatchObject({method:'manual',startLine:1,endLine:2});const thread=f.store.getThread(who,f.thread.threadId);expect(thread.anchor).toEqual(original.anchor);expect(thread.messages).toEqual(original.messages);expect(thread.state).toBe('open');const events=f.store.events(who,f.reviewId)as any[];expect(events.some(e=>e.kind==='thread.reanchored'&&JSON.parse(e.data_json).fileId===next)).toBe(true);}finally{f.close();}});
test('CR-059 verified rename projects while unrelated path stays unavailable',()=>{const f=fixture();try{const same='before\nstart\nconcern\nend\nafter\n',next=f.snap(same,'src/entry.ts','inode1','src/main.ts');expect(f.store.project(who,f.thread.threadId,next).status).toBe('exact');const unrelated=f.snap(same,'src/unrelated.ts','inode1');expect(f.store.project(who,f.thread.threadId,unrelated).status).toBe('missing');expect(f.store.getThread(who,f.thread.threadId).source.newPath).toBe('src/main.ts');}finally{f.close();}});
test('CR-059 a verified Git rename can map to the new side without a working-tree inode',()=>{const f=fixture();try{const old='before\nstart\nconcern\nend\nafter\n';const next=f.store.capture(who,f.reviewId,{workspaceId:'ws',worktreeId:'wt',mode:'staged',base:'commit1',head:'index1',capturedAt:new Date().toISOString(),files:[{oldPath:'src/main.ts',newPath:'src/entry.ts',oldText:old,newText:old,change:'renamed',fileIdentity:null}]},m()).files[0]!;expect(f.store.project(who,f.thread.threadId,next)).toMatchObject({status:'exact',side:'new'});}finally{f.close();}});
test('CR-059 claimed rename with a different old-side blob is not verified',()=>{const f=fixture();try{const different='before\nstart\nconcern\nend\nafter\nplus\n';const next=f.store.capture(who,f.reviewId,{workspaceId:'ws',worktreeId:'wt',mode:'staged',base:'commit1',head:'index1',capturedAt:new Date().toISOString(),files:[{oldPath:'src/main.ts',newPath:'src/entry.ts',oldText:different,newText:different,change:'renamed',fileIdentity:null}]},m()).files[0]!;expect(f.store.project(who,f.thread.threadId,next).status).toBe('missing');}finally{f.close();}});
test('CR-060 deleted and recreated file never inherits anchor by path or bytes',()=>{const f=fixture();try{const next=f.snap('before\nstart\nconcern\nend\nafter\n','src/main.ts','replacement-inode');expect(f.store.project(who,f.thread.threadId,next).status).toBe('missing');expect(f.store.getThread(who,f.thread.threadId).source.fileId).toBe(f.file);}finally{f.close();}});
test('CR-060 unknown file identity never assumes path or identical bytes prove continuity',()=>{const f=fixture();try{const same='before\nstart\nconcern\nend\nafter\n';const noIdentity=f.snap(same,'src/main.ts',null!);expect(f.store.project(who,f.thread.threadId,noIdentity).status).toBe('missing');const noOldIdentity=f.snap(same,'src/no-id.ts',null!);const thread=f.store.createThread(who,f.reviewId,{fileId:noOldIdentity,side:'source',range:{startLine:3,endLine:3},body:'unknown inode'},m());const next=f.snap(same,'src/no-id.ts','inode2');expect(f.store.project(who,thread.threadId,next).status).toBe('missing');}finally{f.close();}});
test('CR-103 resolved remap requires reopen confirmation and retains old resolution evidence',()=>{const f=fixture();try{f.store.resolveThread(who,f.thread.threadId,{explanation:'Addressed S1',fileId:f.file,evidence:['check:original']},m(1));const next=f.snap('new range\n');expect(()=>f.store.reanchor(who,f.thread.threadId,{fileId:next,side:'source',range:{startLine:1,endLine:1}},m(2))).toThrow('reopen-and-re-anchor');expect(f.store.getThread(who,f.thread.threadId).state).toBe('resolved');f.store.reanchor(who,f.thread.threadId,{fileId:next,side:'source',range:{startLine:1,endLine:1},reopen:true},m(2));expect(f.store.getThread(who,f.thread.threadId).state).toBe('open');const old=(f.store.events(who,f.reviewId)as any[]).find(e=>e.kind==='thread.resolved');expect(JSON.parse(old.data_json)).toMatchObject({fileId:f.file,evidence:['check:original']});}finally{f.close();}});
